-- Migration 0: foundation — profiles, signup trigger, RLS.
-- See CLAUDE.md "Build order suggestion" step 0.
--
-- IDs: we use plain gen_random_uuid() (UUIDv4) for our own PKs — "stupid simple",
-- native, no custom function. Sorting is handled by created_at + index, not PK
-- order. Column type stays uuid, so we can switch to v7 later with no type change.
-- (See CLAUDE.md "Decision reversal: plain UUIDv4 over UUIDv7".) profiles.id is the
-- exception: it equals auth.users.id, not generated by us.

-- ---------------------------------------------------------------------------
-- Roles
-- ---------------------------------------------------------------------------
-- Only two app roles this weekend (CLAUDE.md "Roles"). Couriers are NOT users.
-- Admin operates via the Supabase dashboard, so it is not part of this enum.
create type public.user_role as enum ('customer', 'shop');

-- ---------------------------------------------------------------------------
-- profiles — 1:1 with auth.users, carries the role.
-- ---------------------------------------------------------------------------
-- id is NOT generated by us: it equals auth.users.id (Supabase-managed v4 uuid).
-- Version mismatch is irrelevant to FK integrity (CLAUDE.md "IDs — UUIDv7").
create table public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  email      text not null,
  full_name  text,
  phone      text,
  role       public.user_role not null default 'customer',
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Signup trigger — create a profile row whenever an auth user is created.
-- ---------------------------------------------------------------------------
-- Self-serve signups default to 'customer'. Admin-created shop accounts pass
-- role + full_name via user_metadata, which we read here.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data ->> 'full_name',
    coalesce(
      (new.raw_user_meta_data ->> 'role')::public.user_role,
      'customer'
    )
  );
  return new;
end;
$$;

-- Harden: the trigger fires regardless of EXECUTE grants (it runs as the function
-- owner), so revoke direct RPC access — clients must never call this themselves.
revoke execute on function public.handle_new_user() from anon, authenticated, public;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
-- A user may read and update only their own profile. Inserts happen via the
-- trigger above (security definer), never directly from the client. No delete
-- policy: profiles are removed by the auth.users cascade.
alter table public.profiles enable row level security;

create policy "profiles_select_own"
  on public.profiles for select
  to authenticated
  using (id = (select auth.uid()));

create policy "profiles_update_own"
  on public.profiles for update
  to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));
