-- Migration 0: foundation — UUIDv7 generator, profiles, signup trigger.
-- See CLAUDE.md "Build order suggestion" step 0 and "IDs — UUIDv7".

-- ---------------------------------------------------------------------------
-- UUIDv7 generator
-- ---------------------------------------------------------------------------
-- Native uuidv7() needs Postgres 18. Supabase hosted may still be on PG17, so
-- we ship the well-known PL/pgSQL implementation (Fabio Lima) and use it as the
-- default for all OUR own primary keys. Time-sortable + good B-tree locality.
-- If/when on PG18, this can be swapped for `default uuidv7()` with no type change.
create or replace function public.uuid_generate_v7()
returns uuid
language plpgsql
volatile
as $$
begin
  return encode(
    set_bit(
      set_bit(
        overlay(
          uuid_send(gen_random_uuid())
          placing substring(
            int8send(floor(extract(epoch from clock_timestamp()) * 1000)::bigint)
            from 3
          )
          from 1 for 6
        ),
        52, 1
      ),
      53, 1
    ),
    'hex'
  )::uuid;
end;
$$;

-- ---------------------------------------------------------------------------
-- Roles
-- ---------------------------------------------------------------------------
-- Only two app roles this weekend (CLAUDE.md "Roles"). Couriers are NOT users.
-- Admin operates via the Supabase dashboard, so it is not part of this enum.
create type public.user_role as enum ('customer', 'shop');

-- ---------------------------------------------------------------------------
-- profiles — 1:1 with auth.users, carries the role.
-- ---------------------------------------------------------------------------
-- id is NOT generated by us: it equals auth.users.id (Supabase-managed v4 uuid).
-- Version mismatch is irrelevant to FK integrity (CLAUDE.md "IDs — UUIDv7").
create table public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  email      text not null,
  full_name  text,
  phone      text,
  role       public.user_role not null default 'customer',
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Signup trigger — create a profile row whenever an auth user is created.
-- ---------------------------------------------------------------------------
-- Self-serve signups default to 'customer'. Admin-created shop accounts pass
-- role + full_name via user_metadata, which we read here.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data ->> 'full_name',
    coalesce(
      (new.raw_user_meta_data ->> 'role')::public.user_role,
      'customer'
    )
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------
-- A user may read and update only their own profile. Inserts happen via the
-- trigger above (security definer), never directly from the client. No delete
-- policy: profiles are removed by the auth.users cascade.
alter table public.profiles enable row level security;

create policy "profiles_select_own"
  on public.profiles for select
  to authenticated
  using (id = (select auth.uid()));

create policy "profiles_update_own"
  on public.profiles for update
  to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));
